In [8]:
'''
Topics : NumPy

Set 1:
•	Create a 3×3 array of all True Boolean values
•	Extract odd numbers from an array
•	Replace all odd numbers with -1
•	Reverse columns of a 2D array
•	Get indices of elements greater than 5 [hint: check where method of numpy]
•	Access last row - last column

Set 2:
•	Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]
•	Create a 5×5 array with 1 on border and 0 inside
•	Create a random array of 10×10: perform stats (min, max, mean, std)
•	Broadcast a 1D array over a 2D array [all possible scenarios]
•	Sort a 2D array by column 1 [hint: check method argsort()]

Set 3:

•	Find common elements between two arrays [with and without using intersect1d, use isin() instead]
•	Subtract row mean from each row of a 2D array
•	Given a 4×4 array, swap the first half rows with the second half rows
•	Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).
•	From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).
'''

'''
Topics : NumPy

Set 1:
•	Create a 3×3 array of all True Boolean values
•	Extract odd numbers from an array
•	Replace all odd numbers with -1
•	Reverse columns of a 2D array
•	Get indices of elements greater than 5 [hint: check where method of numpy]
•	Access last row - last column

Set 2:
•	Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]
•	Create a 5×5 array with 1 on border and 0 inside
•	Create a random array of 10×10: perform stats (min, max, mean, std)
•	Broadcast a 1D array over a 2D array [all possible scenarios]
•	Sort a 2D array by column 1 [hint: check method argsort()]

Set 3:
•	Find common elements between two arrays [with and without using intersect1d, use isin() instead]
•	Subtract row mean from each row of a 2D array
•	Given a 4×4 array, swap the first half rows with the second half rows
•	Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).
•	From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).
'''


'\nTopics : NumPy\n\nSet 1:\n•\tCreate a 3×3 array of all True Boolean values\n•\tExtract odd numbers from an array\n•\tReplace all odd numbers with -1\n•\tReverse columns of a 2D array\n•\tGet indices of elements greater than 5 [hint: check where method of numpy]\n•\tAccess last row - last column\n\nSet 2:\n•\tNormalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]\n•\tCreate a 5×5 array with 1 on border and 0 inside\n•\tCreate a random array of 10×10: perform stats (min, max, mean, std)\n•\tBroadcast a 1D array over a 2D array [all possible scenarios]\n•\tSort a 2D array by column 1 [hint: check method argsort()]\n\nSet 3:\n•\tFind common elements between two arrays [with and without using intersect1d, use isin() instead]\n•\tSubtract row mean from each row of a 2D array\n•\tGiven a 4×4 array, swap the first half rows with the second half rows\n•\tGiven a 1D array of random numbers, find the indices of the 5 largest values (no 

In [ ]:
'''
Set 1:
•	Create a 3×3 array of all True Boolean values
•	Extract odd numbers from an array
•	Replace all odd numbers with -1
•	Reverse columns of a 2D array
•	Get indices of elements greater than 5 [hint: check where method of numpy]
•	Access last row - last column
'''


In [66]:
import numpy as np

In [12]:
# Create a 3×3 array of all True Boolean values
arr=np.full(9,True).reshape(3,3)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [22]:
arr = np.arange(1,10)
arr[arr%2==1]=-1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [39]:
arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,6]])
arr_2d.ndim

2

In [50]:
np.flip(arr_2d, axis=1)

array([[5, 4, 3, 2, 1],
       [6, 9, 8, 7, 6]])

In [56]:
row,col = np.where(arr_2d > 5)
np.stack((row,col),axis=1)

array([[1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4]])

In [57]:
arr_2d

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 6]])

In [60]:
arr_2d[1][-1]

np.int64(6)

In [ ]:
# Set 2:
# Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]


In [68]:
# Create a 5×5 array with 1 on border and 0 inside
ones=np.ones[(5,5)]
ones

TypeError: 'function' object is not subscriptable

In [62]:
# Create a random array of 10×10: perform stats (min, max, mean, std)


In [ ]:
# Broadcast a 1D array over a 2D array [all possible scenarios]


In [ ]:
# Sort a 2D array by column 1 [hint: check method argsort()]