In [16]:
import numpy as np

In [ ]:
# Create a 3×3 array of all True Boolean values

In [18]:
arr_b = np.full(9, True).reshape(3,3)
arr_b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Extract odd numbers from an array

In [20]:
arr = np.arange(3, 12).reshape(3,3)
arr

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
arr_odd =arr[arr%2!=0]
arr_odd

array([ 3,  5,  7,  9, 11])

In [ ]:
# Replace all odd numbers with -1

In [24]:
arr[arr%2!=0]=-1
arr

array([[-1,  4, -1],
       [ 6, -1,  8],
       [-1, 10, -1]])

In [ ]:
# Reverse columns of a 2D array

In [26]:
arr[:,::-1]

array([[-1,  4, -1],
       [ 8, -1,  6],
       [-1, 10, -1]])

In [28]:
arr

array([[-1,  4, -1],
       [ 6, -1,  8],
       [-1, 10, -1]])

In [ ]:
# Get indices of elements greater than 5 [hint: check where method of numpy]

In [30]:
index=np.where(arr>5)
index

(array([1, 1, 2]), array([0, 2, 1]))

In [32]:
index=np.argwhere(arr>5)
index

array([[1, 0],
       [1, 2],
       [2, 1]])

In [ ]:
# Access last row - last column

In [34]:
arr[-1:,-1:]

array([[-1]])

In [ ]:
# Normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

In [112]:
arr1 = np.array([10,20,30,40,50])
norm = (arr1 - arr1.min()) / (arr1.max() - arr1.min())
print(norm)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create a 5×5 array with 1 on border and 0 inside

In [36]:
arr1 = np.full(25,1).reshape(5,5)
arr1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
arr1[1:-1,1:-1]=0
arr1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# Create a random array of 10×10: perform stats (min, max, mean, std)

In [40]:
arr2=np.random.randint(100,size=(5,5))
arr2

array([[10,  5, 39, 89, 73],
       [96,  4, 81, 27,  6],
       [33, 49, 91, 14, 87],
       [29, 68, 57, 70, 79],
       [47, 10,  1, 41, 16]], dtype=int32)

In [42]:
arr2.min()

np.int32(1)

In [43]:
arr2.max()

np.int32(96)

In [44]:
arr2.mean()

np.float64(44.88)

In [45]:
arr2.std()

np.float64(31.455772125319065)

In [ ]:
# Broadcast a 1D array over a 2D array [all possible scenarios]

In [61]:
a=np.array([[8,21,4,5,4],[3,4,5,6,7]])
b=np.array([9,4,5,2,7])
num=a+b
num

array([[17, 25,  9,  7, 11],
       [12,  8, 10,  8, 14]])

In [ ]:
# Sort a 2D array by column 1 [hint: check method argsort()]

In [65]:
num = np.array([[10,  5, 39, 89, 73],
                [96,  4, 81, 27,  6],
                [33, 49, 91, 14, 87],
                [29, 68, 57, 70, 79],
                [47, 10,  1, 41, 16]
               ])
sorted_arr = num[num[:,1].argsort()]
sorted_arr

array([[96,  4, 81, 27,  6],
       [10,  5, 39, 89, 73],
       [47, 10,  1, 41, 16],
       [33, 49, 91, 14, 87],
       [29, 68, 57, 70, 79]])

In [74]:
# Find common elements between two arrays [with and without using intersect1d, use isin() instead]

In [77]:
a=np.array([8,21,4,5,4])
b=np.array([9,4,5,2,7])
common = np.intersect1d(a,b)
common

array([4, 5])

In [78]:
# Subtract row mean from each row of a 2D array

In [81]:
arr1 = np.array([[5,2,8],[9,5,3]])
mean_arr = arr1.mean(axis=1, keepdims=True)
final = arr1-mean_arr
final

array([[ 0.        , -3.        ,  3.        ],
       [ 3.33333333, -0.66666667, -2.66666667]])

In [82]:
# Given a 4×4 array, swap the first half rows with the second half rows

In [89]:
arr1 = np.arange(16).reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
arr1[[0,1,2,3]]=arr1[[2,3,0,1]]
arr1

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [96]:
# Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).

In [106]:
unsorted_arr = np.random.randint(4,89,10)
unsorted_arr

array([70, 69, 30, 66, 12, 84, 23, 36, 27,  5], dtype=int32)

In [110]:
top_5_indices = np.argsort(unsorted_arr)[-5:][::-1]
unsorted_arr[top_5_indices]

array([84, 70, 69, 66, 36], dtype=int32)

In [95]:
# From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).

In [111]:
arr = np.array([[1,2],
                [3,4],
                [1,2]])

unique = np.unique(arr, axis=0)
print(unique)

[[1 2]
 [3 4]]
