In [4]:
import numpy as np

arr=([1,2,3,4,5,6,7])
arr


[1, 2, 3, 4, 5, 6, 7]

In [7]:
arr=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
arr.astype(float)

array([1., 2., 3., 4., 5., 6., 7.])

In [9]:
type(arr)

numpy.ndarray

In [14]:
arr=np.arange(10)
arr.size

10

In [19]:
arr=arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
arr.shape

(2, 5)

In [22]:
arr.dtype

dtype('int64')

In [23]:
zeros=np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
ones=np.ones([3,2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
arr=np.random.randint(1,15,6)
arr

array([13,  5, 14,  2,  1,  2], dtype=int32)

In [28]:
arr=np.random.random([3,3])
arr

array([[0.19629643, 0.07005621, 0.47798603],
       [0.7822479 , 0.98705081, 0.18283734],
       [0.01359906, 0.64488534, 0.24143502]])

In [34]:
arr=np.full(18,True).reshape(3,6)
arr

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [39]:
arr=np.linspace(2,20,20)
arr

array([ 2.        ,  2.94736842,  3.89473684,  4.84210526,  5.78947368,
        6.73684211,  7.68421053,  8.63157895,  9.57894737, 10.52631579,
       11.47368421, 12.42105263, 13.36842105, 14.31578947, 15.26315789,
       16.21052632, 17.15789474, 18.10526316, 19.05263158, 20.        ])

In [37]:
arr=np.empty([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
arr = np.identity([3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])