In [2]:
import numpy as np

In [3]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
for e in arr:
    print(e)

[0 1 2]
[3 4 5]
[6 7 8]


In [5]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8


In [6]:
np.ravel(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2=np.array([[11,12,13,14],[15,16,17,18]])
arr2

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [9]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [10]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [19]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.repeat(arr,2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8])

In [21]:
arr= np.array([[2,3],[4,5]])
arr

array([[2, 3],
       [4, 5]])

In [22]:
np.repeat(arr,(1,2,2,3))

array([2, 3, 3, 4, 4, 5, 5, 5])

In [34]:
arr= np.array([2,3])
arr

array([2, 3])

In [35]:
np.tile(arr, 4)

array([2, 3, 2, 3, 2, 3, 2, 3])

In [36]:
arr

array([2, 3])

In [41]:
arr=np.insert(arr, 1, 4)
arr
arr = [1,2,3,4,5]
arr

[1, 2, 3, 4, 5]

In [42]:
arr1=np.array([3,4])
np.concatenate([arr, arr1])

array([1, 2, 3, 4, 5, 3, 4])

In [29]:
arr = np.random.randint(2,15,30).reshape(5,6)
arr

array([[12, 12,  2,  5, 11,  9],
       [ 5, 10, 10, 12,  3,  6],
       [11, 10, 13,  5,  8,  4],
       [ 4, 11, 11,  6,  7,  8],
       [13,  2, 13,  5,  2, 10]], dtype=int32)

In [32]:
arr[2][2]

np.int32(13)